services:
  ml-api:
    image: ml-scaler:latest
    container_name: ml-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-baseline
    ports:
      - "9092:9090"   # 9092 avoids conflict with K8s Prometheus on 9090/9091
    volumes:
      - ./monitoring/prometheus-baseline.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - ml-api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-baseline
    ports:
      - "3002:3000"   # 3002 avoids conflict with K8s Grafana on 3001
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - prometheus
